### ISSUE TITLE
Homing Z 100

### ISSUE THREAD

**Issue by paul-ferragut** [timschneider/CNCGraf7Post#1]
Thank you for providing this Post processor! for the gcode to work with my CNC "Haase AL 1290" I removed the part Homing Z 100 to 0

**Comment by timschneider** [comment]
@paul-ferragut this is actually a setting you can change out of fusion. So i would consider tihs as no issue.

**Comment by paul-ferragut** [comment]
Yes absolutely, not an issue, I was always getting an error in CNCGraf "The Height of axis Z equals: 140.00! Please check in the dialogue window "Positions" and "Machine parameters" the zero point und the monitoring settings of Z axis."
This was because of Homing Z, now I set homing Z around 10
